### ISSUE TITLE
Tracking more than 100 channels

### ISSUE THREAD

**Issue by spathizilla** [megadrive/TwitchOnlineTracker#3]
If you have the tracker to track more than 100 channels, it will throw a 400 error from the API endpoint. I believe the API docs say you can only query 100 channels at a time.

**Comment by megadrive** [comment]
A proper scalable solution would be to have a query scheduler where it will query the first 100, then the next 100 and so on and then loop around but I had intended for this to be a pretty barebones project.

In the interim, you can use `tracker.tracked.size` to detect when you're tracking too many and take action on it.

In future, I may add such functionality though. Thanks.
